import {
  useEffect,
  useMemo,
  useState,
} from "react";

import {
  NarrativeCard,
} from "./StoryShared";


const START_YEAR = 2026;
const END_YEAR = 2049;


const SCENARIOS = [
  {
    id: "continuity",
    label: "Continuity",
    timeseries:
      "/model/Continuity_timeseries.json",
  },

  {
    id: "density",
    label: "Density",
    timeseries:
      "/model/Density_timeseries.json",
  },

  {
    id: "overgrowth",
    label: "Overgrowth",
    timeseries:
      "/model/Overgrowth_timeseries.json",
  },

  {
  id: "degrowth",
  label: "Degrowth",
  timeseries:
    "/model/Degrowth_timeseries.json",
  },

];


const KPI_OPTIONS = [
  {
    id: "education",
    tabLabel: "Education",
    title: "School Students",
    field: "SchoolStudents",

    description:
      "Projected students the education system would need to support.",

    format: (value) =>
      value == null
        ? "—"
        : `${Math.round(value).toLocaleString()} students`,
  },

  {
    id: "healthcare",
    tabLabel: "Healthcare",
    title: "Hospital Beds Required",
    field: "HospitalRequiredBeds",

    description:
      "Hospital capacity required to serve the projected population.",

    format: (value) =>
      value == null
        ? "—"
        : `${Math.round(value).toLocaleString()} beds`,
  },

  {
    id: "energy",
    tabLabel: "Energy",
    title: "Electricity Demand",
    field: "ElectricityDemand_kWh_year",

    description:
      "Annual electricity demand generated by residents and economic activity.",

    format: (value) =>
      value == null
        ? "—"
        : `${(value / 1_000_000).toFixed(1)}M kWh / year`,
  },

  {
    id: "mobility",
    tabLabel: "Mobility",
    title: "Road Space Per Person",
    field: "RoadPerCapita_m",

    description:
      "How much of Andorra's road network is available per resident.",

    format: (value) =>
      value == null
        ? "—"
        : `${value.toFixed(2)} m / person`,
  },

  {
    id: "gdp",
    tabLabel: "GDP",
    title: "GDP Per Capita",
    field: "GDPpc",

    description:
      "Projected economic output per resident under each future.",

    format: (value) =>
      value == null
        ? "—"
        : new Intl.NumberFormat(
            "en-US",
            {
              style: "currency",
              currency: "EUR",
              maximumFractionDigits: 0,
            }
          ).format(value),
  },
];


function findYear(rows, year) {
  return (
    rows?.find(
      (row) =>
        Number(row.Year) === year
    ) ?? null
  );
}


function formatPopulation(value) {
  if (value == null) return "—";

  return Math.round(
    value
  ).toLocaleString();
}


function formatNumber(value) {
  return Math.round(value).toLocaleString();
}


function formatMillions(value) {
  return `${(value / 1_000_000).toFixed(1)} million`;
}


function formatEuro(value) {
  return new Intl.NumberFormat(
    "en-US",
    {
      style: "currency",
      currency: "EUR",
      maximumFractionDigits: 0,
    }
  ).format(value);
}


function percentMore(larger, smaller) {
  if (!larger || !smaller) return 0;

  return Math.round(
    ((larger - smaller) / smaller) * 100
  );
}


export default function DailyLifeSection({
  step,
}) {
  const [
    selectedYear,
    setSelectedYear,
  ] = useState(START_YEAR);

  const [
    selectedKpiId,
    setSelectedKpiId,
  ] = useState("education");

  const [
    scenarioData,
    setScenarioData,
  ] = useState({});

  const [
    error,
    setError,
  ] = useState(false);

  const [
  takeawayUnlocked,
  setTakeawayUnlocked,
] = useState(false);


  /*
   * Load the same three scenario
   * timeseries used by the previous section.
   */
  useEffect(() => {
    const controller =
      new AbortController();


    Promise.all(
      SCENARIOS.map(
        async (scenario) => {
          const response =
            await fetch(
              scenario.timeseries,
              {
                signal:
                  controller.signal,
              }
            );


          if (!response.ok) {
            throw new Error(
              `Could not load ${scenario.timeseries}`
            );
          }


          const rows =
            await response.json();


          return [
            scenario.id,
            rows,
          ];
        }
      )
    )

      .then((entries) => {
        setScenarioData(
          Object.fromEntries(entries)
        );
      })

      .catch((err) => {
        if (err.name !== "AbortError") {
          console.error(
            "Failed to load Daily Life scenario data:",
            err
          );

          setError(true);
        }
      });


    return () => {
      controller.abort();
    };
  }, []);


  const selectedKpi =
    useMemo(
      () =>
        KPI_OPTIONS.find(
          (kpi) =>
            kpi.id === selectedKpiId
        ) ?? KPI_OPTIONS[0],

      [selectedKpiId]
    );


  /*
   * Find the MAXIMUM value of the selected
   * KPI across:
   *
   * all three scenarios
   * AND
   * all years 2026–2049.
   *
   * This gives us one fixed bar scale.
   *
   * So dragging the year slider does NOT
   * secretly rescale the bars every year.
   */
  const scaleMax =
    useMemo(() => {
      const values =
        SCENARIOS.flatMap(
          (scenario) =>
            (
              scenarioData[
                scenario.id
              ] ?? []
            )

              .filter(
                (row) =>
                  Number(row.Year) >=
                    START_YEAR &&
                  Number(row.Year) <=
                    END_YEAR
              )

              .map((row) =>
                Number(
                  row[
                    selectedKpi.field
                  ]
                )
              )

              .filter(
                (value) =>
                  Number.isFinite(value)
              )
        );


      return values.length
        ? Math.max(...values)
        : 0;
    }, [
      scenarioData,
      selectedKpi,
    ]);


  const selectedRows =
    useMemo(() => {
      return SCENARIOS.map(
        (scenario) => {
          const row =
            findYear(
              scenarioData[
                scenario.id
              ],
              selectedYear
            );


          const value =
            row
              ? Number(
                  row[
                    selectedKpi.field
                  ]
                )
              : null;


          const barPercent =
            value != null &&
            scaleMax > 0
              ? Math.max(
                  0,
                  Math.min(
                    100,
                    (value /
                      scaleMax) *
                      100
                  )
                )
              : 0;


          return {
            ...scenario,
            row,
            value,
            barPercent,
          };
        }
      );
    }, [
      scenarioData,
      selectedYear,
      selectedKpi,
      scaleMax,
    ]);

    const takeaway =
  useMemo(() => {
    const continuity =
      findYear(
        scenarioData.continuity,
        END_YEAR
      );

    const density =
      findYear(
        scenarioData.density,
        END_YEAR
      );

    const overgrowth =
      findYear(
        scenarioData.overgrowth,
        END_YEAR
      );
    
    const degrowth =
      findYear(
        scenarioData.degrowth,
        END_YEAR
      );


    if (
      !continuity ||
      !density ||
      !degrowth ||
      !overgrowth
    ) {
      return null;
    }

    if (
  selectedKpiId ===
  "education"
) {
  const overgrowthStudents =
    Math.round(
      overgrowth.SchoolStudents
    );

  const continuityStudents =
    Math.round(
      continuity.SchoolStudents
    );

  const densityStudents =
    Math.round(
      density.SchoolStudents
    );

  const degrowthStudents =
    Math.round(
      degrowth.SchoolStudents
    );


  return {
    label: "Education",

    text:
      `By 2049, Overgrowth reaches ${formatNumber(
        overgrowthStudents
      )} students — about ${formatNumber(
        overgrowthStudents -
          continuityStudents
      )} more than Continuity and ${formatNumber(
        overgrowthStudents -
          densityStudents
      )} more than Density. ` +

      `The model corresponds to roughly ${Math.round(
        overgrowth.SchoolSchools
      )} schools under Overgrowth, compared with about ${Math.round(
        continuity.SchoolSchools
      )} under Continuity and ${Math.round(
        density.SchoolSchools
      )} under Density. ` +

      `Degrowth moves in the opposite direction, falling to about ${formatNumber(
        degrowthStudents
      )} students and roughly ${Math.round(
        degrowth.SchoolSchools
      )} modeled schools.`,
  };
}


if (
  selectedKpiId ===
  "healthcare"
) {
  const overgrowthBeds =
    Math.round(
      overgrowth.HospitalRequiredBeds
    );

  const continuityBeds =
    Math.round(
      continuity.HospitalRequiredBeds
    );

  const densityBeds =
    Math.round(
      density.HospitalRequiredBeds
    );

  const degrowthBeds =
    Math.round(
      degrowth.HospitalRequiredBeds
    );


  return {
    label: "Healthcare",

    text:
      `Overgrowth creates the largest healthcare capacity requirement. ` +

      `By 2049, the model requires about ${formatNumber(
        overgrowthBeds
      )} hospital beds, compared with ${formatNumber(
        continuityBeds
      )} under Continuity and ${formatNumber(
        densityBeds
      )} under Density. ` +

      `That is roughly ${formatNumber(
        overgrowthBeds -
          continuityBeds
      )} more beds than Continuity and ${formatNumber(
        overgrowthBeds -
          densityBeds
      )} more than Density. ` +

      `Degrowth requires only about ${formatNumber(
        degrowthBeds
      )} beds by 2049, showing how strongly future healthcare demand follows the size of the population.`,
  };
}


if (
  selectedKpiId ===
  "energy"
) {
  const overgrowthEnergy =
    overgrowth
      .ElectricityDemand_kWh_year;

  const continuityEnergy =
    continuity
      .ElectricityDemand_kWh_year;

  const densityEnergy =
    density
      .ElectricityDemand_kWh_year;

  const degrowthEnergy =
    degrowth
      .ElectricityDemand_kWh_year;


  return {
    label: "Energy",

    text:
      `By 2049, annual electricity demand reaches about ${formatMillions(
        overgrowthEnergy
      )} kWh under Overgrowth, compared with ${formatMillions(
        continuityEnergy
      )} kWh under Continuity and ${formatMillions(
        densityEnergy
      )} kWh under Density. ` +

      `That makes Overgrowth demand roughly ${percentMore(
        overgrowthEnergy,
        continuityEnergy
      )}% higher than Continuity and ${percentMore(
        overgrowthEnergy,
        densityEnergy
      )}% higher than Density. ` +

      `Degrowth falls to about ${formatMillions(
        degrowthEnergy
      )} kWh per year, the lowest demand of the four modeled futures.`,
  };
}


if (
  selectedKpiId ===
  "mobility"
) {
  const overgrowthRoad =
    overgrowth.RoadPerCapita_m;

  const continuityRoad =
    continuity.RoadPerCapita_m;

  const densityRoad =
    density.RoadPerCapita_m;

  const degrowthRoad =
    degrowth.RoadPerCapita_m;


  return {
    label: "Mobility",

    text:
      `The modeled road network remains highly constrained as population changes. ` +

      `By 2049, Density provides about ${densityRoad.toFixed(
        2
      )} meters of road per resident, compared with ${continuityRoad.toFixed(
        2
      )} meters under Continuity and only ${overgrowthRoad.toFixed(
        2
      )} meters under Overgrowth. ` +

      `Overgrowth therefore leaves about ${Math.round(
        (1 -
          overgrowthRoad /
            densityRoad) *
          100
      )}% less road per resident than Density. ` +

      `Degrowth produces the opposite effect: with fewer residents sharing the same modeled road network, road space rises to ${degrowthRoad.toFixed(
        2
      )} meters per person.`,
  };
}


if (
  selectedKpiId ===
  "gdp"
) {
  return {
    label: "GDP",

    text:
      `The higher-growth future also produces much greater modeled economic output per resident. ` +

      `By 2049, GDP per capita reaches about ${formatEuro(
        overgrowth.GDPpc
      )} under Overgrowth, compared with ${formatEuro(
        density.GDPpc
      )} under Density and ${formatEuro(
        continuity.GDPpc
      )} under Continuity. ` +

      `Density finishes with fewer residents than Continuity but higher GDP per capita, while Overgrowth combines the highest per-capita output with the greatest infrastructure demands shown across the other indicators. ` +

      `Degrowth illustrates the economic side of that tradeoff: GDP per capita falls to about ${formatEuro(
        degrowth.GDPpc
      )}, the lowest of the four scenarios.`,
  };
}

    return null;
  }, [
    scenarioData,
    selectedKpiId,
  ]);

  useEffect(() => {
  if (
    selectedYear ===
    END_YEAR
  ) {
    setTakeawayUnlocked(true);
  }
}, [selectedYear]);


  return (
    <>

      <NarrativeCard>
        <p>{step.annotation}</p>
      </NarrativeCard>


      <div className="story-impact-explorer">

        {/* KPI SELECTOR */}
        <div className="story-impact-tabs">

          {KPI_OPTIONS.map(
            (kpi) => (
              <button
                key={kpi.id}
                type="button"

                className={
                  selectedKpiId ===
                  kpi.id
                    ? "story-impact-tab story-impact-tab--active"
                    : "story-impact-tab"
                }

                onClick={() =>
                  setSelectedKpiId(
                    kpi.id
                  )
                }

                aria-pressed={
                  selectedKpiId ===
                  kpi.id
                }
              >
                {kpi.tabLabel}
              </button>
            )
          )}

        </div>


        {/* KPI TITLE */}
        <div className="story-impact-heading">

          <span>
            Effects on Daily Life
          </span>

          <h3>
            {selectedKpi.title}
          </h3>

          <p>
            {selectedKpi.description}
          </p>

        </div>

        {/* 2049 TAKEAWAY */}
<div
  className={
    takeawayUnlocked
      ? "story-impact-takeaway story-impact-takeaway--unlocked"
      : "story-impact-takeaway story-impact-takeaway--locked"
  }
>

  {!takeawayUnlocked ? (
    <>
      <span className="story-impact-takeaway-label">
        2049 Takeaway
      </span>

      <p>
        Slide to 2049 to reveal the
        long-term implications.
      </p>
    </>
  ) : (
    <>
      <span className="story-impact-takeaway-label">
        2049 Takeaway ·{" "}
        {takeaway?.label}
      </span>

      <p>
        {takeaway?.text}
      </p>
    </>
  )}

</div>


{/* SAME YEAR SLIDER STYLE
    AS SCENARIOS TO 2049 */}
<div className="story-scenarios-slider story-daily-life-slider"></div>


        {/* THREE-SCENARIO COMPARISON */}
        <div className="story-impact-comparison">

          {selectedRows.map(
            ({
              id,
              label,
              row,
              value,
              barPercent,
            }) => (

              <div
                key={id}
                className="story-impact-row"
              >

                <div className="story-impact-scenario">

                  <strong>
                    {label}
                  </strong>

                  <span>
                    Population{" "}
                    {formatPopulation(
                      row?.Pop
                    )}
                  </span>

                </div>


                <div className="story-impact-bar-track">

                  <div
                    className="story-impact-bar-fill"

                    style={{
                      width:
                        `${barPercent}%`,
                    }}
                  />

                </div>


                <div className="story-impact-value">

                  {selectedKpi.format(
                    value
                  )}

                </div>

              </div>
            )
          )}

        </div>


        {/* SAME YEAR SLIDER STYLE
            AS SCENARIOS TO 2049 */}
        <div className="story-scenarios-slider story-daily-life-slider">

          <div className="story-year-slider-header">

            <span>
              {START_YEAR}
            </span>

            <strong>
              {selectedYear}
            </strong>

            <span>
              {END_YEAR}
            </span>

          </div>


          <input
            type="range"

            min={START_YEAR}
            max={END_YEAR}
            step="1"

            value={selectedYear}

            onChange={(event) =>
              setSelectedYear(
                Number(
                  event.target.value
                )
              )
            }

            aria-label="Daily life comparison year"
          />

        </div>


        <p className="story-impact-scale-note">
          Bar lengths use one fixed scale for this metric across
          all three scenarios and all years from 2026–2049.
        </p>


        {error && (
          <p className="story-scenario-data-error">
            Some scenario data could not be loaded.
          </p>
        )}

      </div>

    </>
  );
}