import { useEffect, useMemo, useState } from "react";

const START_YEAR = 2026;
const END_YEAR = 2049;
const SHARED_2026_BAR = 52;

const SCENARIOS = [
  {
    id: "degrowth",
    label: "Degrowth",
    timeseries: "/model/Degrowth_timeseries.json",
    color: "#89928a",
  },
  {
    id: "continuity",
    label: "Continuity",
    timeseries: "/model/Continuity_timeseries.json",
    color: "#d4d0c8",
  },
  {
    id: "density",
    label: "Density",
    timeseries: "/model/Density_timeseries.json",
    color: "#8f2634",
  },
  {
    id: "overgrowth",
    label: "Overgrowth",
    timeseries: "/model/Overgrowth_timeseries.json",
    color: "#c66c76",
  },
];

const KPI_OPTIONS = [
  {
    id: "education",
    tabLabel: "Education",
    title: "School Students",
    field: "SchoolStudents",
    description: "Projected students the education system would need to support.",
    format: (value) =>
      value == null ? "—" : `${Math.round(value).toLocaleString()} students`,
    formatDelta: (value) => `${Math.round(Math.abs(value)).toLocaleString()} students`,
  },
  {
    id: "healthcare",
    tabLabel: "Healthcare",
    title: "Hospital Beds Required",
    field: "HospitalRequiredBeds",
    description: "Hospital capacity required to serve the projected population.",
    format: (value) =>
      value == null ? "—" : `${Math.round(value).toLocaleString()} beds`,
    formatDelta: (value) => `${Math.round(Math.abs(value)).toLocaleString()} beds`,
  },
  {
    id: "energy",
    tabLabel: "Energy",
    title: "Electricity Demand",
    field: "ElectricityDemand_kWh_year",
    description: "Annual electricity demand generated by residents and economic activity.",
    format: (value) =>
      value == null ? "—" : `${(value / 1_000_000).toFixed(1)}M kWh / year`,
    formatDelta: (value) => `${(Math.abs(value) / 1_000_000).toFixed(1)}M kWh / year`,
  },
  {
    id: "mobility",
    tabLabel: "Mobility",
    title: "Road Space Per Person",
    field: "RoadPerCapita_m",
    description: "How much of Andorra's modeled road network is available per resident.",
    format: (value) =>
      value == null ? "—" : `${value.toFixed(2)} m / person`,
    formatDelta: (value) => `${Math.abs(value).toFixed(2)} m / person`,
  },
  {
    id: "gdp",
    tabLabel: "GDP",
    title: "GDP Per Capita",
    field: "GDPpc",
    description: "Projected economic output per resident under each future.",
    format: (value) =>
      value == null
        ? "—"
        : new Intl.NumberFormat("en-US", {
            style: "currency",
            currency: "EUR",
            maximumFractionDigits: 0,
          }).format(value),
    formatDelta: (value) =>
      new Intl.NumberFormat("en-US", {
        style: "currency",
        currency: "EUR",
        maximumFractionDigits: 0,
      }).format(Math.abs(value)),
  },
];

function findYear(rows, year) {
  return rows?.find((row) => Number(row.Year) === year) ?? null;
}

function formatPopulation(value) {
  if (value == null) return "—";
  return Math.round(value).toLocaleString();
}

export default function DailyLifeSection({ step }) {
  const [selectedYear, setSelectedYear] = useState(START_YEAR);
  const [selectedKpiId, setSelectedKpiId] = useState("education");
  const [scenarioData, setScenarioData] = useState({});
  const [error, setError] = useState(false);

  useEffect(() => {
    const controller = new AbortController();

    Promise.all(
      SCENARIOS.map(async (scenario) => {
        const response = await fetch(scenario.timeseries, {
          signal: controller.signal,
        });

        if (!response.ok) {
          throw new Error(`Could not load ${scenario.timeseries}`);
        }

        return [scenario.id, await response.json()];
      })
    )
      .then((entries) => setScenarioData(Object.fromEntries(entries)))
      .catch((err) => {
        if (err.name !== "AbortError") {
          console.error("Failed to load Daily Life scenario data:", err);
          setError(true);
        }
      });

    return () => controller.abort();
  }, []);

  const selectedKpi = useMemo(
    () => KPI_OPTIONS.find((kpi) => kpi.id === selectedKpiId) ?? KPI_OPTIONS[0],
    [selectedKpiId]
  );

  const scaleMax = useMemo(() => {
    const values = SCENARIOS.flatMap((scenario) =>
      (scenarioData[scenario.id] ?? [])
        .filter(
          (row) =>
            Number(row.Year) >= START_YEAR && Number(row.Year) <= END_YEAR
        )
        .map((row) => Number(row[selectedKpi.field]))
        .filter(Number.isFinite)
    );

    return values.length ? Math.max(...values) : 0;
  }, [scenarioData, selectedKpi]);

  const selectedRows = useMemo(() => {
    return SCENARIOS.map((scenario) => {
      const row = findYear(scenarioData[scenario.id], selectedYear);
      const value = row ? Number(row[selectedKpi.field]) : null;

      const actualPercent =
        value != null && scaleMax > 0
          ? Math.max(0, Math.min(100, (value / scaleMax) * 100))
          : 0;

      return {
        ...scenario,
        row,
        value,
        barPercent: selectedYear === START_YEAR ? SHARED_2026_BAR : actualPercent,
      };
    });
  }, [scenarioData, selectedYear, selectedKpi, scaleMax]);

  const takeaway = useMemo(() => {
    const rows2049 = SCENARIOS.map((scenario) => {
      const row = findYear(scenarioData[scenario.id], END_YEAR);
      const value = row ? Number(row[selectedKpi.field]) : null;
      return { ...scenario, value };
    }).filter((item) => Number.isFinite(item.value));

    if (rows2049.length !== SCENARIOS.length) return null;

    const sorted = [...rows2049].sort((a, b) => a.value - b.value);
    const low = sorted[0];
    const high = sorted[sorted.length - 1];
    const spread = high.value - low.value;

    return {
      label: `${selectedKpi.tabLabel} · 2049 long view`,
      text: `${high.label} reaches ${selectedKpi.format(
        high.value
      )}, while ${low.label} reaches ${selectedKpi.format(
        low.value
      )}. The modeled spread between those futures is ${selectedKpi.formatDelta(
        spread
      )}.`,
    };
  }, [scenarioData, selectedKpi]);

  return (
    <div className="story-impact-explorer">
      <div className="story-impact-intro-grid">
        <div className="story-impact-intro-copy">
          <p className="story-editorial-lede">{step.annotation}</p>
        </div>

        <aside className="story-impact-takeaway story-impact-takeaway--persistent">
          <span className="story-impact-takeaway-label">
            {takeaway?.label ?? "2049 long view"}
          </span>
          <p>
            {takeaway?.text ??
              "The long-term comparison will appear here when scenario data finishes loading."}
          </p>
        </aside>
      </div>

      <div className="story-impact-tabs" aria-label="Daily life metric">
        {KPI_OPTIONS.map((kpi) => (
          <button
            key={kpi.id}
            type="button"
            className={
              selectedKpiId === kpi.id
                ? "story-impact-tab story-impact-tab--active"
                : "story-impact-tab"
            }
            onClick={() => setSelectedKpiId(kpi.id)}
            aria-pressed={selectedKpiId === kpi.id}
          >
            {kpi.tabLabel}
          </button>
        ))}
      </div>

      <div className="story-impact-heading">
        <span>Compare the futures</span>
        <h3>{selectedKpi.title}</h3>
        <p>{selectedKpi.description}</p>
      </div>

      <div className="story-impact-comparison">
        {selectedRows.map(({ id, label, row, value, barPercent, color }) => (
          <div key={id} className="story-impact-row">
            <div className="story-impact-scenario">
              <strong>{label}</strong>
              <span>Population {formatPopulation(row?.Pop)}</span>
            </div>

            <div className="story-impact-bar-track">
              <div
                className="story-impact-bar-fill"
                style={{
                  width: `${barPercent}%`,
                  "--story-bar-color": color,
                }}
              />
            </div>

            <div className="story-impact-value">{selectedKpi.format(value)}</div>
          </div>
        ))}
      </div>

      <div className="story-scenarios-slider story-daily-life-slider">
        <div className="story-year-slider-header">
          <span>{START_YEAR}</span>
          <strong>{selectedYear}</strong>
          <span>{END_YEAR}</span>
        </div>

        <input
          type="range"
          min={START_YEAR}
          max={END_YEAR}
          step="1"
          value={selectedYear}
          onChange={(event) => setSelectedYear(Number(event.target.value))}
          aria-label="Daily life comparison year"
        />
      </div>

      <p className="story-impact-scale-note">
        2026 is shown as a shared visual baseline so every scenario begins at the
        same bar length. From 2027 onward, bar lengths follow the modeled values
        on one fixed scale for the selected metric.
      </p>

      {error && (
        <p className="story-scenario-data-error">
          Some scenario data could not be loaded.
        </p>
      )}
    </div>
  );
}
